spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwe123
    url: jdbc:mysql://127.0.0.1:3306/cloth
  jpa:
    show-sql: true
    database: mysql
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: ihrm-system
server:
  port: 8082